// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.route.implementation;

import com.azure.maps.route.fluent.models.GetRouteRangeResponseInner;
import com.azure.maps.route.models.GetRouteRangeResponse;
import com.azure.maps.route.models.RouteRange;
import com.azure.maps.route.models.RouteResponseReport;

public final class GetRouteRangeResponseImpl implements GetRouteRangeResponse {
    private GetRouteRangeResponseInner innerObject;

    private final com.azure.maps.route.RouteManager serviceManager;

    GetRouteRangeResponseImpl(
        GetRouteRangeResponseInner innerObject, com.azure.maps.route.RouteManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String formatVersion() {
        return this.innerModel().formatVersion();
    }

    public RouteRange reachableRange() {
        return this.innerModel().reachableRange();
    }

    public RouteResponseReport report() {
        return this.innerModel().report();
    }

    public GetRouteRangeResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.route.RouteManager manager() {
        return this.serviceManager;
    }
}
