// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.route.implementation;

import com.azure.maps.route.fluent.models.RouteMatrixResponseInner;
import com.azure.maps.route.models.RouteMatrixResponse;
import com.azure.maps.route.models.RouteMatrixResult;
import com.azure.maps.route.models.RouteMatrixSummary;
import java.util.Collections;
import java.util.List;

public final class RouteMatrixResponseImpl implements RouteMatrixResponse {
    private RouteMatrixResponseInner innerObject;

    private final com.azure.maps.route.RouteManager serviceManager;

    RouteMatrixResponseImpl(RouteMatrixResponseInner innerObject, com.azure.maps.route.RouteManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String formatVersion() {
        return this.innerModel().formatVersion();
    }

    public List<List<RouteMatrixResult>> matrix() {
        List<List<RouteMatrixResult>> inner = this.innerModel().matrix();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public RouteMatrixSummary summary() {
        return this.innerModel().summary();
    }

    public RouteMatrixResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.route.RouteManager manager() {
        return this.serviceManager;
    }
}
