// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.weather.models.CurrentConditions;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The CurrentConditionsResponse model. */
@Fluent
public final class CurrentConditionsResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(CurrentConditionsResponseInner.class);

    /*
     * Detailed current weather conditions.
     */
    @JsonProperty(value = "results")
    private List<CurrentConditions> results;

    /**
     * Get the results property: Detailed current weather conditions.
     *
     * @return the results value.
     */
    public List<CurrentConditions> results() {
        return this.results;
    }

    /**
     * Set the results property: Detailed current weather conditions.
     *
     * @param results the results value to set.
     * @return the CurrentConditionsResponseInner object itself.
     */
    public CurrentConditionsResponseInner withResults(List<CurrentConditions> results) {
        this.results = results;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (results() != null) {
            results().forEach(e -> e.validate());
        }
    }
}
