// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.weather.models.SevereWeatherAlert;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** This object is returned from a successful Get Severe Weather Alerts call. */
@Fluent
public final class SevereWeatherAlertsResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(SevereWeatherAlertsResponseInner.class);

    /*
     * A list of all severe weather alerts for the queried location.
     */
    @JsonProperty(value = "results")
    private List<SevereWeatherAlert> results;

    /**
     * Get the results property: A list of all severe weather alerts for the queried location.
     *
     * @return the results value.
     */
    public List<SevereWeatherAlert> results() {
        return this.results;
    }

    /**
     * Set the results property: A list of all severe weather alerts for the queried location.
     *
     * @param results the results value to set.
     * @return the SevereWeatherAlertsResponseInner object itself.
     */
    public SevereWeatherAlertsResponseInner withResults(List<SevereWeatherAlert> results) {
        this.results = results;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (results() != null) {
            results().forEach(e -> e.validate());
        }
    }
}
