// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.weather.models.WeatherAlongRouteSummary;
import com.azure.maps.weather.models.WeatherWaypoint;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** This object is returned from a successful Weather Along Route. */
@Fluent
public final class WeatherAlongRouteResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(WeatherAlongRouteResponseInner.class);

    /*
     * Short summary of the weather along the route.
     */
    @JsonProperty(value = "summary")
    private WeatherAlongRouteSummary summary;

    /*
     * Data for each waypoint returned in the same order as specified in the
     * request.
     */
    @JsonProperty(value = "waypoints")
    private List<WeatherWaypoint> waypoints;

    /**
     * Get the summary property: Short summary of the weather along the route.
     *
     * @return the summary value.
     */
    public WeatherAlongRouteSummary summary() {
        return this.summary;
    }

    /**
     * Set the summary property: Short summary of the weather along the route.
     *
     * @param summary the summary value to set.
     * @return the WeatherAlongRouteResponseInner object itself.
     */
    public WeatherAlongRouteResponseInner withSummary(WeatherAlongRouteSummary summary) {
        this.summary = summary;
        return this;
    }

    /**
     * Get the waypoints property: Data for each waypoint returned in the same order as specified in the request.
     *
     * @return the waypoints value.
     */
    public List<WeatherWaypoint> waypoints() {
        return this.waypoints;
    }

    /**
     * Set the waypoints property: Data for each waypoint returned in the same order as specified in the request.
     *
     * @param waypoints the waypoints value to set.
     * @return the WeatherAlongRouteResponseInner object itself.
     */
    public WeatherAlongRouteResponseInner withWaypoints(List<WeatherWaypoint> waypoints) {
        this.waypoints = waypoints;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (summary() != null) {
            summary().validate();
        }
        if (waypoints() != null) {
            waypoints().forEach(e -> e.validate());
        }
    }
}
