// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.implementation;

import com.azure.maps.search.fluent.models.SearchPoiCategoryTreeResponseInner;
import com.azure.maps.search.models.PoiCategoryResult;
import com.azure.maps.search.models.SearchPoiCategoryTreeResponse;
import java.util.Collections;
import java.util.List;

public final class SearchPoiCategoryTreeResponseImpl implements SearchPoiCategoryTreeResponse {
    private SearchPoiCategoryTreeResponseInner innerObject;

    private final com.azure.maps.search.SearchManager serviceManager;

    SearchPoiCategoryTreeResponseImpl(
        SearchPoiCategoryTreeResponseInner innerObject, com.azure.maps.search.SearchManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<PoiCategoryResult> poiCategories() {
        List<PoiCategoryResult> inner = this.innerModel().poiCategories();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public SearchPoiCategoryTreeResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.search.SearchManager manager() {
        return this.serviceManager;
    }
}
