// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation;

import com.azure.maps.weather.fluent.models.DailyIndicesResponseInner;
import com.azure.maps.weather.models.DailyIndex;
import com.azure.maps.weather.models.DailyIndicesResponse;
import java.util.Collections;
import java.util.List;

public final class DailyIndicesResponseImpl implements DailyIndicesResponse {
    private DailyIndicesResponseInner innerObject;

    private final com.azure.maps.weather.WeatherManager serviceManager;

    DailyIndicesResponseImpl(
        DailyIndicesResponseInner innerObject, com.azure.maps.weather.WeatherManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<DailyIndex> results() {
        List<DailyIndex> inner = this.innerModel().results();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public DailyIndicesResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.weather.WeatherManager manager() {
        return this.serviceManager;
    }
}
