// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation;

import com.azure.maps.weather.fluent.models.DailyForecastResponseInner;
import com.azure.maps.weather.models.DailyForecast;
import com.azure.maps.weather.models.DailyForecastResponse;
import com.azure.maps.weather.models.DailyForecastSummary;
import java.util.Collections;
import java.util.List;

public final class DailyForecastResponseImpl implements DailyForecastResponse {
    private DailyForecastResponseInner innerObject;

    private final com.azure.maps.weather.WeatherManager serviceManager;

    DailyForecastResponseImpl(
        DailyForecastResponseInner innerObject, com.azure.maps.weather.WeatherManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public DailyForecastSummary summary() {
        return this.innerModel().summary();
    }

    public List<DailyForecast> forecasts() {
        List<DailyForecast> inner = this.innerModel().forecasts();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public DailyForecastResponseInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.weather.WeatherManager manager() {
        return this.serviceManager;
    }
}
