// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.render.implementation;

import com.azure.maps.render.fluent.models.GetCopyrightForWorldResultInner;
import com.azure.maps.render.models.GetCopyrightForWorldResult;
import com.azure.maps.render.models.RegionCopyrights;
import java.util.Collections;
import java.util.List;

public final class GetCopyrightForWorldResultImpl implements GetCopyrightForWorldResult {
    private GetCopyrightForWorldResultInner innerObject;

    private final com.azure.maps.render.RenderManager serviceManager;

    GetCopyrightForWorldResultImpl(
        GetCopyrightForWorldResultInner innerObject, com.azure.maps.render.RenderManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String formatVersion() {
        return this.innerModel().formatVersion();
    }

    public List<String> generalCopyrights() {
        List<String> inner = this.innerModel().generalCopyrights();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public List<RegionCopyrights> regions() {
        List<RegionCopyrights> inner = this.innerModel().regions();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public GetCopyrightForWorldResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.render.RenderManager manager() {
        return this.serviceManager;
    }
}
