// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The AirAndPollen model. */
@Fluent
public final class AirAndPollen {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(AirAndPollen.class);

    /*
     * Name of the pollen or pollutant. For example, grass, mold, weed, air
     * quality, tree and UV index.
     */
    @JsonProperty(value = "name")
    private String name;

    /*
     * Value of the given type above. Values associated with mold, grass, weed
     * and tree are in units of parts per cubic meter. Both air quality and UV
     * are indices, so they are unitless.
     */
    @JsonProperty(value = "value")
    private Integer value;

    /*
     * Category of the air quality or pollution type. For example, low, high,
     * good, moderate, unhealthy, hazardous.
     */
    @JsonProperty(value = "category")
    private String category;

    /*
     * Value associated with the air quality or pollution category. These
     * values range from 1 to 6. 1 implying good conditions, 6 implying
     * hazardous conditions.
     */
    @JsonProperty(value = "categoryValue")
    private Integer categoryValue;

    /*
     * Only exists for air quality. Examples include ozone and particle
     * pollution.
     */
    @JsonProperty(value = "type")
    private String type;

    /**
     * Get the name property: Name of the pollen or pollutant. For example, grass, mold, weed, air quality, tree and UV
     * index.
     *
     * @return the name value.
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name property: Name of the pollen or pollutant. For example, grass, mold, weed, air quality, tree and UV
     * index.
     *
     * @param name the name value to set.
     * @return the AirAndPollen object itself.
     */
    public AirAndPollen withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the value property: Value of the given type above. Values associated with mold, grass, weed and tree are in
     * units of parts per cubic meter. Both air quality and UV are indices, so they are unitless.
     *
     * @return the value value.
     */
    public Integer value() {
        return this.value;
    }

    /**
     * Set the value property: Value of the given type above. Values associated with mold, grass, weed and tree are in
     * units of parts per cubic meter. Both air quality and UV are indices, so they are unitless.
     *
     * @param value the value value to set.
     * @return the AirAndPollen object itself.
     */
    public AirAndPollen withValue(Integer value) {
        this.value = value;
        return this;
    }

    /**
     * Get the category property: Category of the air quality or pollution type. For example, low, high, good, moderate,
     * unhealthy, hazardous.
     *
     * @return the category value.
     */
    public String category() {
        return this.category;
    }

    /**
     * Set the category property: Category of the air quality or pollution type. For example, low, high, good, moderate,
     * unhealthy, hazardous.
     *
     * @param category the category value to set.
     * @return the AirAndPollen object itself.
     */
    public AirAndPollen withCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Get the categoryValue property: Value associated with the air quality or pollution category. These values range
     * from 1 to 6. 1 implying good conditions, 6 implying hazardous conditions.
     *
     * @return the categoryValue value.
     */
    public Integer categoryValue() {
        return this.categoryValue;
    }

    /**
     * Set the categoryValue property: Value associated with the air quality or pollution category. These values range
     * from 1 to 6. 1 implying good conditions, 6 implying hazardous conditions.
     *
     * @param categoryValue the categoryValue value to set.
     * @return the AirAndPollen object itself.
     */
    public AirAndPollen withCategoryValue(Integer categoryValue) {
        this.categoryValue = categoryValue;
        return this;
    }

    /**
     * Get the type property: Only exists for air quality. Examples include ozone and particle pollution.
     *
     * @return the type value.
     */
    public String type() {
        return this.type;
    }

    /**
     * Set the type property: Only exists for air quality. Examples include ozone and particle pollution.
     *
     * @param type the type value to set.
     * @return the AirAndPollen object itself.
     */
    public AirAndPollen withType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
