// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.models;

import com.azure.maps.weather.fluent.models.CurrentConditionsResponseInner;
import java.util.List;

/** An immutable client-side representation of CurrentConditionsResponse. */
public interface CurrentConditionsResponse {
    /**
     * Gets the results property: Detailed current weather conditions.
     *
     * @return the results value.
     */
    List<CurrentConditions> results();

    /**
     * Gets the inner com.azure.maps.weather.fluent.models.CurrentConditionsResponseInner object.
     *
     * @return the inner object.
     */
    CurrentConditionsResponseInner innerModel();
}
