// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The latest status on the alert in the current area. */
@Fluent
public final class LatestStatus {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(LatestStatus.class);

    /*
     * The latest status keyword for the alert, in the specified language. By
     * default, returned in English (en-US).
     */
    @JsonProperty(value = "localized")
    private String localized;

    /*
     * Latest status keyword for the alert, in English (en-US).
     */
    @JsonProperty(value = "english")
    private LatestStatusKeyword english;

    /**
     * Get the localized property: The latest status keyword for the alert, in the specified language. By default,
     * returned in English (en-US).
     *
     * @return the localized value.
     */
    public String localized() {
        return this.localized;
    }

    /**
     * Set the localized property: The latest status keyword for the alert, in the specified language. By default,
     * returned in English (en-US).
     *
     * @param localized the localized value to set.
     * @return the LatestStatus object itself.
     */
    public LatestStatus withLocalized(String localized) {
        this.localized = localized;
        return this;
    }

    /**
     * Get the english property: Latest status keyword for the alert, in English (en-US).
     *
     * @return the english value.
     */
    public LatestStatusKeyword english() {
        return this.english;
    }

    /**
     * Set the english property: Latest status keyword for the alert, in English (en-US).
     *
     * @param english the english value to set.
     * @return the LatestStatus object itself.
     */
    public LatestStatus withEnglish(LatestStatusKeyword english) {
        this.english = english;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
