// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Description of a severe weather alert. */
@Fluent
public final class SevereWeatherAlertDescription {
    /*
     * Description of the alert in the specified language. By default English
     * (en-US) is returned if the language parameter is not specified in the
     * request.
     */
    @JsonProperty(value = "localized")
    private String description;

    /*
     * Description of the alert in English (en-US).
     */
    @JsonProperty(value = "english")
    private String status;

    /**
     * Get the description property: Description of the alert in the specified language. By default English (en-US) is
     * returned if the language parameter is not specified in the request.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Description of the alert in the specified language. By default English (en-US) is
     * returned if the language parameter is not specified in the request.
     *
     * @param description the description value to set.
     * @return the SevereWeatherAlertDescription object itself.
     */
    public SevereWeatherAlertDescription setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the status property: Description of the alert in English (en-US).
     *
     * @return the status value.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Set the status property: Description of the alert in English (en-US).
     *
     * @param status the status value to set.
     * @return the SevereWeatherAlertDescription object itself.
     */
    public SevereWeatherAlertDescription setStatus(String status) {
        this.status = status;
        return this;
    }
}
