// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** This object is returned from a successful Get Air Quality call. */
@Fluent
public final class AirQualityResult {
    /*
     * A list of all air quality results for the queried location.
     */
    @JsonProperty(value = "results")
    private List<AirQuality> airQualityResults;

    /*
     * The is the link to the next page of the features returned. If it's the
     * last page, no this field.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the airQualityResults property: A list of all air quality results for the queried location.
     *
     * @return the airQualityResults value.
     */
    public List<AirQuality> getAirQualityResults() {
        return this.airQualityResults;
    }

    /**
     * Set the airQualityResults property: A list of all air quality results for the queried location.
     *
     * @param airQualityResults the airQualityResults value to set.
     * @return the AirQualityResult object itself.
     */
    public AirQualityResult setAirQualityResults(List<AirQuality> airQualityResults) {
        this.airQualityResults = airQualityResults;
        return this;
    }

    /**
     * Get the nextLink property: The is the link to the next page of the features returned. If it's the last page, no
     * this field.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The is the link to the next page of the features returned. If it's the last page, no
     * this field.
     *
     * @param nextLink the nextLink value to set.
     * @return the AirQualityResult object itself.
     */
    public AirQualityResult setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
