// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The DailyHistoricalActualsResult model. */
@Fluent
public final class DailyHistoricalActualsResult {
    /*
     * Historical actuals for each requested day.
     */
    @JsonProperty(value = "results")
    private List<DailyHistoricalActuals> historicalActuals;

    /*
     * The is the link to the next page of the features returned. If it's the
     * last page, no this field.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the historicalActuals property: Historical actuals for each requested day.
     *
     * @return the historicalActuals value.
     */
    public List<DailyHistoricalActuals> getHistoricalActuals() {
        return this.historicalActuals;
    }

    /**
     * Set the historicalActuals property: Historical actuals for each requested day.
     *
     * @param historicalActuals the historicalActuals value to set.
     * @return the DailyHistoricalActualsResult object itself.
     */
    public DailyHistoricalActualsResult setHistoricalActuals(List<DailyHistoricalActuals> historicalActuals) {
        this.historicalActuals = historicalActuals;
        return this;
    }

    /**
     * Get the nextLink property: The is the link to the next page of the features returned. If it's the last page, no
     * this field.
     *
     * @return the nextLink value.
     */
    public String getNextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink property: The is the link to the next page of the features returned. If it's the last page, no
     * this field.
     *
     * @param nextLink the nextLink value to set.
     * @return the DailyHistoricalActualsResult object itself.
     */
    public DailyHistoricalActualsResult setNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }
}
