// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The WaypointForecast model. */
@Fluent
public final class WaypointForecast {
    /*
     * Numeric value representing an image that displays the `iconPhrase`.
     * Please refer to [Weather Service
     * Concepts](https://aka.ms/AzureMapsWeatherConcepts) for details.
     */
    @JsonProperty(value = "iconCode")
    private IconCode iconCode;

    /*
     * A displayable short phrase describing the forecasted conditions and
     * precipitation intensity/type.
     */
    @JsonProperty(value = "shortPhrase")
    private String shortDescription;

    /*
     * Indicates the time of the day. True indicates 'day',', false indicates
     * 'night.
     */
    @JsonProperty(value = "isDayTime")
    private Boolean isDaytime;

    /*
     * Percent representing cloud cover.
     */
    @JsonProperty(value = "cloudCover")
    private Integer cloudCover;

    /*
     * Specific value of a given unit related to weather.
     */
    @JsonProperty(value = "temperature")
    private WeatherValue temperature;

    /*
     * Wind details being returned including speed and direction.
     */
    @JsonProperty(value = "wind")
    private WindDetails wind;

    /*
     * Wind details being returned including speed and direction.
     */
    @JsonProperty(value = "windGust")
    private WindDetails windGust;

    /*
     * Precipitation forecast of the weather along the route.
     */
    @JsonProperty(value = "precipitation")
    private WeatherAlongRoutePrecipitation precipitation;

    /*
     * Estimation of thunderstorm intensity on an open scale. A value of 0
     * means there is no thunderstorm; values of 1 and higher mean there is a
     * thunderstorm in increasing intensity.
     */
    @JsonProperty(value = "lightningCount")
    private Integer lightningCount;

    /*
     * A rating that indicates how blinding the sun is for the driver.
     */
    @JsonProperty(value = "sunGlare")
    private SunGlare sunGlare;

    /*
     * Description of the weather hazard affecting the trip.
     */
    @JsonProperty(value = "hazards")
    private WeatherHazards hazards;

    /*
     * List of weather hazard notifications.
     */
    @JsonProperty(value = "notifications")
    private List<WeatherNotification> notifications;

    /**
     * Get the iconCode property: Numeric value representing an image that displays the `iconPhrase`. Please refer to
     * [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for details.
     *
     * @return the iconCode value.
     */
    public IconCode getIconCode() {
        return this.iconCode;
    }

    /**
     * Set the iconCode property: Numeric value representing an image that displays the `iconPhrase`. Please refer to
     * [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for details.
     *
     * @param iconCode the iconCode value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setIconCode(IconCode iconCode) {
        this.iconCode = iconCode;
        return this;
    }

    /**
     * Get the shortDescription property: A displayable short phrase describing the forecasted conditions and
     * precipitation intensity/type.
     *
     * @return the shortDescription value.
     */
    public String getShortDescription() {
        return this.shortDescription;
    }

    /**
     * Set the shortDescription property: A displayable short phrase describing the forecasted conditions and
     * precipitation intensity/type.
     *
     * @param shortDescription the shortDescription value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
        return this;
    }

    /**
     * Get the isDaytime property: Indicates the time of the day. True indicates 'day',', false indicates 'night.
     *
     * @return the isDaytime value.
     */
    public Boolean isDaytime() {
        return this.isDaytime;
    }

    /**
     * Set the isDaytime property: Indicates the time of the day. True indicates 'day',', false indicates 'night.
     *
     * @param isDaytime the isDaytime value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setIsDaytime(Boolean isDaytime) {
        this.isDaytime = isDaytime;
        return this;
    }

    /**
     * Get the cloudCover property: Percent representing cloud cover.
     *
     * @return the cloudCover value.
     */
    public Integer getCloudCover() {
        return this.cloudCover;
    }

    /**
     * Set the cloudCover property: Percent representing cloud cover.
     *
     * @param cloudCover the cloudCover value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setCloudCover(Integer cloudCover) {
        this.cloudCover = cloudCover;
        return this;
    }

    /**
     * Get the temperature property: Specific value of a given unit related to weather.
     *
     * @return the temperature value.
     */
    public WeatherValue getTemperature() {
        return this.temperature;
    }

    /**
     * Set the temperature property: Specific value of a given unit related to weather.
     *
     * @param temperature the temperature value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setTemperature(WeatherValue temperature) {
        this.temperature = temperature;
        return this;
    }

    /**
     * Get the wind property: Wind details being returned including speed and direction.
     *
     * @return the wind value.
     */
    public WindDetails getWind() {
        return this.wind;
    }

    /**
     * Set the wind property: Wind details being returned including speed and direction.
     *
     * @param wind the wind value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setWind(WindDetails wind) {
        this.wind = wind;
        return this;
    }

    /**
     * Get the windGust property: Wind details being returned including speed and direction.
     *
     * @return the windGust value.
     */
    public WindDetails getWindGust() {
        return this.windGust;
    }

    /**
     * Set the windGust property: Wind details being returned including speed and direction.
     *
     * @param windGust the windGust value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setWindGust(WindDetails windGust) {
        this.windGust = windGust;
        return this;
    }

    /**
     * Get the precipitation property: Precipitation forecast of the weather along the route.
     *
     * @return the precipitation value.
     */
    public WeatherAlongRoutePrecipitation getPrecipitation() {
        return this.precipitation;
    }

    /**
     * Set the precipitation property: Precipitation forecast of the weather along the route.
     *
     * @param precipitation the precipitation value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setPrecipitation(WeatherAlongRoutePrecipitation precipitation) {
        this.precipitation = precipitation;
        return this;
    }

    /**
     * Get the lightningCount property: Estimation of thunderstorm intensity on an open scale. A value of 0 means there
     * is no thunderstorm; values of 1 and higher mean there is a thunderstorm in increasing intensity.
     *
     * @return the lightningCount value.
     */
    public Integer getLightningCount() {
        return this.lightningCount;
    }

    /**
     * Set the lightningCount property: Estimation of thunderstorm intensity on an open scale. A value of 0 means there
     * is no thunderstorm; values of 1 and higher mean there is a thunderstorm in increasing intensity.
     *
     * @param lightningCount the lightningCount value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setLightningCount(Integer lightningCount) {
        this.lightningCount = lightningCount;
        return this;
    }

    /**
     * Get the sunGlare property: A rating that indicates how blinding the sun is for the driver.
     *
     * @return the sunGlare value.
     */
    public SunGlare getSunGlare() {
        return this.sunGlare;
    }

    /**
     * Set the sunGlare property: A rating that indicates how blinding the sun is for the driver.
     *
     * @param sunGlare the sunGlare value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setSunGlare(SunGlare sunGlare) {
        this.sunGlare = sunGlare;
        return this;
    }

    /**
     * Get the hazards property: Description of the weather hazard affecting the trip.
     *
     * @return the hazards value.
     */
    public WeatherHazards getHazards() {
        return this.hazards;
    }

    /**
     * Set the hazards property: Description of the weather hazard affecting the trip.
     *
     * @param hazards the hazards value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setHazards(WeatherHazards hazards) {
        this.hazards = hazards;
        return this;
    }

    /**
     * Get the notifications property: List of weather hazard notifications.
     *
     * @return the notifications value.
     */
    public List<WeatherNotification> getNotifications() {
        return this.notifications;
    }

    /**
     * Set the notifications property: List of weather hazard notifications.
     *
     * @param notifications the notifications value to set.
     * @return the WaypointForecast object itself.
     */
    public WaypointForecast setNotifications(List<WeatherNotification> notifications) {
        this.notifications = notifications;
        return this;
    }
}
