// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The WeatherValueYear model. */
@Fluent
public final class WeatherValueYear {
    /*
     * Rounded value.
     */
    @JsonProperty(value = "value")
    private Float value;

    /*
     * Type of unit for the returned value.
     */
    @JsonProperty(value = "unit")
    private String unit;

    /*
     * Numeric ID value associated with the type of unit being displayed. Can
     * be used for unit translation. Please refer to [Weather Service
     * Concepts](https://aka.ms/AzureMapsWeatherConcepts) for details.
     */
    @JsonProperty(value = "unitType")
    private Integer unitType;

    /*
     * Year the value occurred.
     */
    @JsonProperty(value = "year")
    private Integer year;

    /**
     * Get the value property: Rounded value.
     *
     * @return the value value.
     */
    public Float getValue() {
        return this.value;
    }

    /**
     * Set the value property: Rounded value.
     *
     * @param value the value value to set.
     * @return the WeatherValueYear object itself.
     */
    public WeatherValueYear setValue(Float value) {
        this.value = value;
        return this;
    }

    /**
     * Get the unit property: Type of unit for the returned value.
     *
     * @return the unit value.
     */
    public String getUnit() {
        return this.unit;
    }

    /**
     * Set the unit property: Type of unit for the returned value.
     *
     * @param unit the unit value to set.
     * @return the WeatherValueYear object itself.
     */
    public WeatherValueYear setUnit(String unit) {
        this.unit = unit;
        return this;
    }

    /**
     * Get the unitType property: Numeric ID value associated with the type of unit being displayed. Can be used for
     * unit translation. Please refer to [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for
     * details.
     *
     * @return the unitType value.
     */
    public Integer getUnitType() {
        return this.unitType;
    }

    /**
     * Set the unitType property: Numeric ID value associated with the type of unit being displayed. Can be used for
     * unit translation. Please refer to [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for
     * details.
     *
     * @param unitType the unitType value to set.
     * @return the WeatherValueYear object itself.
     */
    public WeatherValueYear setUnitType(Integer unitType) {
        this.unitType = unitType;
        return this;
    }

    /**
     * Get the year property: Year the value occurred.
     *
     * @return the year value.
     */
    public Integer getYear() {
        return this.year;
    }

    /**
     * Set the year property: Year the value occurred.
     *
     * @param year the year value to set.
     * @return the WeatherValueYear object itself.
     */
    public WeatherValueYear setYear(Integer year) {
        this.year = year;
        return this;
    }
}
