// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.weather.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Specific value of a given unit related to weather. */
@Fluent
public final class WeatherValue {
    /*
     * Rounded value.
     */
    @JsonProperty(value = "value")
    private Float value;

    /*
     * Type of unit for the returned value.
     */
    @JsonProperty(value = "unit")
    private String unitLabel;

    /*
     * Numeric ID value associated with the type of unit being displayed. Can
     * be used for unit translation. Please refer to [Weather Service
     * Concepts](https://aka.ms/AzureMapsWeatherConcepts) for details.
     */
    @JsonProperty(value = "unitType")
    private UnitType unitType;

    /**
     * Get the value property: Rounded value.
     *
     * @return the value value.
     */
    public Float getValue() {
        return this.value;
    }

    /**
     * Set the value property: Rounded value.
     *
     * @param value the value value to set.
     * @return the WeatherValue object itself.
     */
    public WeatherValue setValue(Float value) {
        this.value = value;
        return this;
    }

    /**
     * Get the unitLabel property: Type of unit for the returned value.
     *
     * @return the unitLabel value.
     */
    public String getUnitLabel() {
        return this.unitLabel;
    }

    /**
     * Set the unitLabel property: Type of unit for the returned value.
     *
     * @param unitLabel the unitLabel value to set.
     * @return the WeatherValue object itself.
     */
    public WeatherValue setUnitLabel(String unitLabel) {
        this.unitLabel = unitLabel;
        return this;
    }

    /**
     * Get the unitType property: Numeric ID value associated with the type of unit being displayed. Can be used for
     * unit translation. Please refer to [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for
     * details.
     *
     * @return the unitType value.
     */
    public UnitType getUnitType() {
        return this.unitType;
    }

    /**
     * Set the unitType property: Numeric ID value associated with the type of unit being displayed. Can be used for
     * unit translation. Please refer to [Weather Service Concepts](https://aka.ms/AzureMapsWeatherConcepts) for
     * details.
     *
     * @param unitType the unitType value to set.
     * @return the WeatherValue object itself.
     */
    public WeatherValue setUnitType(UnitType unitType) {
        this.unitType = unitType;
        return this;
    }
}
