// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.models;

import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpRequest;
import com.azure.core.http.rest.ResponseBase;
import com.azure.maps.search.fluent.models.SearchFuzzyBatchResponseInner;

/** Contains all response data for the postSearchFuzzyBatch operation. */
public final class SearchesPostSearchFuzzyBatchResponse
    extends ResponseBase<SearchesPostSearchFuzzyBatchHeaders, SearchFuzzyBatchResponseInner> {
    /**
     * Creates an instance of SearchesPostSearchFuzzyBatchResponse.
     *
     * @param request the request which resulted in this SearchesPostSearchFuzzyBatchResponse.
     * @param statusCode the status code of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param value the deserialized value of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     */
    public SearchesPostSearchFuzzyBatchResponse(
        HttpRequest request,
        int statusCode,
        HttpHeaders rawHeaders,
        SearchFuzzyBatchResponseInner value,
        SearchesPostSearchFuzzyBatchHeaders headers) {
        super(request, statusCode, rawHeaders, value, headers);
    }

    /** @return the deserialized response body. */
    @Override
    public SearchFuzzyBatchResponseInner getValue() {
        return super.getValue();
    }
}
