// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents a date and time. */
@Immutable
public final class SearchResultPoiOpeningHoursTimeRangeTime {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(SearchResultPoiOpeningHoursTimeRangeTime.class);

    /*
     * Represents current day in calendar year in POI time zone.
     */
    @JsonProperty(value = "date", access = JsonProperty.Access.WRITE_ONLY)
    private String date;

    /*
     * Hours are in the 24 hour format in the local time of a POI; possible
     * values are 0 - 23.
     */
    @JsonProperty(value = "hour", access = JsonProperty.Access.WRITE_ONLY)
    private Integer hour;

    /*
     * Minutes are in the local time of a POI; possible values are 0 - 59.
     */
    @JsonProperty(value = "minute", access = JsonProperty.Access.WRITE_ONLY)
    private Integer minute;

    /**
     * Get the date property: Represents current day in calendar year in POI time zone.
     *
     * @return the date value.
     */
    public String date() {
        return this.date;
    }

    /**
     * Get the hour property: Hours are in the 24 hour format in the local time of a POI; possible values are 0 - 23.
     *
     * @return the hour value.
     */
    public Integer hour() {
        return this.hour;
    }

    /**
     * Get the minute property: Minutes are in the local time of a POI; possible values are 0 - 59.
     *
     * @return the minute value.
     */
    public Integer minute() {
        return this.minute;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
