// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.models;

import com.azure.maps.search.fluent.models.SearchPoiCategoryTreeResponseInner;
import java.util.List;

/** An immutable client-side representation of SearchPoiCategoryTreeResponse. */
public interface SearchPoiCategoryTreeResponse {
    /**
     * Gets the poiCategories property: Categories array.
     *
     * @return the poiCategories value.
     */
    List<PoiCategoryResult> poiCategories();

    /**
     * Gets the inner com.azure.maps.search.fluent.models.SearchPoiCategoryTreeResponseInner object.
     *
     * @return the inner object.
     */
    SearchPoiCategoryTreeResponseInner innerModel();
}
