// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.models;

import com.azure.maps.search.fluent.models.SearchAddressReverseCrossStreetResponseInner;
import java.util.List;

/** An immutable client-side representation of SearchAddressReverseCrossStreetResponse. */
public interface SearchAddressReverseCrossStreetResponse {
    /**
     * Gets the summary property: Summary object for a Search Address Reverse Cross Street response.
     *
     * @return the summary value.
     */
    SearchCommonSummary summary();

    /**
     * Gets the addresses property: Addresses array.
     *
     * @return the addresses value.
     */
    List<SearchAddressReverseCrossStreetResult> addresses();

    /**
     * Gets the inner com.azure.maps.search.fluent.models.SearchAddressReverseCrossStreetResponseInner object.
     *
     * @return the inner object.
     */
    SearchAddressReverseCrossStreetResponseInner innerModel();
}
