// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.elevation.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.elevation.models.PointElevationResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The response from a successful Elevation Points request. */
@Immutable
public final class PointsResultInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(PointsResultInner.class);

    /*
     * The response for point/points elevation API. The result will be in same
     * sequence of points listed in request.
     */
    @JsonProperty(value = "data", access = JsonProperty.Access.WRITE_ONLY)
    private List<PointElevationResult> data;

    /**
     * Get the data property: The response for point/points elevation API. The result will be in same sequence of points
     * listed in request.
     *
     * @return the data value.
     */
    public List<PointElevationResult> data() {
        return this.data;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (data() != null) {
            data().forEach(e -> e.validate());
        }
    }
}
