// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.timezone.implementation;

import com.azure.maps.timezone.fluent.models.TimezoneByIdResultInner;
import com.azure.maps.timezone.models.TimezoneById;
import com.azure.maps.timezone.models.TimezoneByIdResult;
import java.time.OffsetDateTime;
import java.util.Collections;
import java.util.List;

public final class TimezoneByIdResultImpl implements TimezoneByIdResult {
    private TimezoneByIdResultInner innerObject;

    private final com.azure.maps.timezone.TimezoneManager serviceManager;

    TimezoneByIdResultImpl(
        TimezoneByIdResultInner innerObject, com.azure.maps.timezone.TimezoneManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public String version() {
        return this.innerModel().version();
    }

    public OffsetDateTime referenceUtcTimestamp() {
        return this.innerModel().referenceUtcTimestamp();
    }

    public List<TimezoneById> timeZones() {
        List<TimezoneById> inner = this.innerModel().timeZones();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public TimezoneByIdResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.timezone.TimezoneManager manager() {
        return this.serviceManager;
    }
}
