// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.creator.models.GreatCircleDistanceResponseResult;
import com.azure.maps.creator.models.GreatCircleDistanceResponseSummary;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** This object is returned from a successful Great Circle Distance call. */
@Immutable
public final class GreatCircleDistanceResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(GreatCircleDistanceResponseInner.class);

    /*
     * Summary object
     */
    @JsonProperty(value = "summary", access = JsonProperty.Access.WRITE_ONLY)
    private GreatCircleDistanceResponseSummary summary;

    /*
     * Result Object
     */
    @JsonProperty(value = "result", access = JsonProperty.Access.WRITE_ONLY)
    private GreatCircleDistanceResponseResult result;

    /**
     * Get the summary property: Summary object.
     *
     * @return the summary value.
     */
    public GreatCircleDistanceResponseSummary summary() {
        return this.summary;
    }

    /**
     * Get the result property: Result Object.
     *
     * @return the result value.
     */
    public GreatCircleDistanceResponseResult result() {
        return this.result;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (summary() != null) {
            summary().validate();
        }
        if (result() != null) {
            result().validate();
        }
    }
}
