// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.management.exception.ManagementError;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.creator.models.LroStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** The response model for a Long-Running Operations API. */
@Fluent
public final class LongRunningOperationResultInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(LongRunningOperationResultInner.class);

    /*
     * The Id for this long-running operation.
     */
    @JsonProperty(value = "operationId")
    private String operationId;

    /*
     * The status state of the request.
     */
    @JsonProperty(value = "status", access = JsonProperty.Access.WRITE_ONLY)
    private LroStatus status;

    /*
     * The created timestamp.
     */
    @JsonProperty(value = "created", access = JsonProperty.Access.WRITE_ONLY)
    private String created;

    /*
     * The error detail.
     */
    @JsonProperty(value = "error")
    private ManagementError error;

    /*
     * The error detail.
     */
    @JsonProperty(value = "warning")
    private ManagementError warning;

    /**
     * Get the operationId property: The Id for this long-running operation.
     *
     * @return the operationId value.
     */
    public String operationId() {
        return this.operationId;
    }

    /**
     * Set the operationId property: The Id for this long-running operation.
     *
     * @param operationId the operationId value to set.
     * @return the LongRunningOperationResultInner object itself.
     */
    public LongRunningOperationResultInner withOperationId(String operationId) {
        this.operationId = operationId;
        return this;
    }

    /**
     * Get the status property: The status state of the request.
     *
     * @return the status value.
     */
    public LroStatus status() {
        return this.status;
    }

    /**
     * Get the created property: The created timestamp.
     *
     * @return the created value.
     */
    public String created() {
        return this.created;
    }

    /**
     * Get the error property: The error detail.
     *
     * @return the error value.
     */
    public ManagementError error() {
        return this.error;
    }

    /**
     * Set the error property: The error detail.
     *
     * @param error the error value to set.
     * @return the LongRunningOperationResultInner object itself.
     */
    public LongRunningOperationResultInner withError(ManagementError error) {
        this.error = error;
        return this;
    }

    /**
     * Get the warning property: The error detail.
     *
     * @return the warning value.
     */
    public ManagementError warning() {
        return this.warning;
    }

    /**
     * Set the warning property: The error detail.
     *
     * @param warning the warning value to set.
     * @return the LongRunningOperationResultInner object itself.
     */
    public LongRunningOperationResultInner withWarning(ManagementError warning) {
        this.warning = warning;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
