// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.fluent.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.creator.models.StylesObject;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The response model for the successful Stateset Get API. */
@Fluent
public final class StatesetGetResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(StatesetGetResponseInner.class);

    /*
     * Description associated with the stateset.
     */
    @JsonProperty(value = "description", access = JsonProperty.Access.WRITE_ONLY)
    private String description;

    /*
     * Dataset ID associated with the stateset.
     */
    @JsonProperty(value = "datasetIds")
    private List<String> datasetIds;

    /*
     * The styles model.
     */
    @JsonProperty(value = "statesetStyle")
    private StylesObject statesetStyle;

    /**
     * Get the description property: Description associated with the stateset.
     *
     * @return the description value.
     */
    public String description() {
        return this.description;
    }

    /**
     * Get the datasetIds property: Dataset ID associated with the stateset.
     *
     * @return the datasetIds value.
     */
    public List<String> datasetIds() {
        return this.datasetIds;
    }

    /**
     * Set the datasetIds property: Dataset ID associated with the stateset.
     *
     * @param datasetIds the datasetIds value to set.
     * @return the StatesetGetResponseInner object itself.
     */
    public StatesetGetResponseInner withDatasetIds(List<String> datasetIds) {
        this.datasetIds = datasetIds;
        return this;
    }

    /**
     * Get the statesetStyle property: The styles model.
     *
     * @return the statesetStyle value.
     */
    public StylesObject statesetStyle() {
        return this.statesetStyle;
    }

    /**
     * Set the statesetStyle property: The styles model.
     *
     * @param statesetStyle the statesetStyle value to set.
     * @return the StatesetGetResponseInner object itself.
     */
    public StatesetGetResponseInner withStatesetStyle(StylesObject statesetStyle) {
        this.statesetStyle = statesetStyle;
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (statesetStyle() != null) {
            statesetStyle().validate();
        }
    }
}
