// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

module com.azure.maps.weather {
    requires transitive com.azure.core.management;

    exports com.azure.maps.weather;
    exports com.azure.maps.weather.fluent;
    exports com.azure.maps.weather.fluent.models;
    exports com.azure.maps.weather.models;

    opens com.azure.maps.weather.fluent.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
    opens com.azure.maps.weather.models to
        com.azure.core,
        com.fasterxml.jackson.databind;
}
