// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.timezone.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Timezone names object. */
@Immutable
public final class TimezoneNames {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(TimezoneNames.class);

    /*
     * The ISO 639-1 language code of the Names
     */
    @JsonProperty(value = "ISO6391LanguageCode", access = JsonProperty.Access.WRITE_ONLY)
    private String iso6391LanguageCode;

    /*
     * Generic Name
     */
    @JsonProperty(value = "Generic", access = JsonProperty.Access.WRITE_ONLY)
    private String generic;

    /*
     * Standard Name
     */
    @JsonProperty(value = "Standard", access = JsonProperty.Access.WRITE_ONLY)
    private String standard;

    /*
     * Daylight Name
     */
    @JsonProperty(value = "Daylight", access = JsonProperty.Access.WRITE_ONLY)
    private String daylight;

    /**
     * Get the iso6391LanguageCode property: The ISO 639-1 language code of the Names.
     *
     * @return the iso6391LanguageCode value.
     */
    public String iso6391LanguageCode() {
        return this.iso6391LanguageCode;
    }

    /**
     * Get the generic property: Generic Name.
     *
     * @return the generic value.
     */
    public String generic() {
        return this.generic;
    }

    /**
     * Get the standard property: Standard Name.
     *
     * @return the standard value.
     */
    public String standard() {
        return this.standard;
    }

    /**
     * Get the daylight property: Daylight Name.
     *
     * @return the daylight value.
     */
    public String daylight() {
        return this.daylight;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
