// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.traffic.models;

import com.azure.maps.traffic.fluent.models.TrafficIncidentDetailResultInner;

/** An immutable client-side representation of TrafficIncidentDetailResult. */
public interface TrafficIncidentDetailResult {
    /**
     * Gets the tm property: Main response element.
     *
     * @return the tm value.
     */
    TrafficIncidentDetailResultTm tm();

    /**
     * Gets the inner com.azure.maps.traffic.fluent.models.TrafficIncidentDetailResultInner object.
     *
     * @return the inner object.
     */
    TrafficIncidentDetailResultInner innerModel();
}
