// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.traffic.models;

import com.azure.maps.traffic.fluent.models.TrafficIncidentViewportResultInner;

/** An immutable client-side representation of TrafficIncidentViewportResult. */
public interface TrafficIncidentViewportResult {
    /**
     * Gets the viewpResp property: Viewport Response object.
     *
     * @return the viewpResp value.
     */
    TrafficIncidentViewportResultViewpResp viewpResp();

    /**
     * Gets the inner com.azure.maps.traffic.fluent.models.TrafficIncidentViewportResultInner object.
     *
     * @return the inner object.
     */
    TrafficIncidentViewportResultInner innerModel();
}
