// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.elevation.implementation;

import com.azure.maps.elevation.fluent.models.BoundingBoxResultInner;
import com.azure.maps.elevation.models.BoundingBoxResult;
import com.azure.maps.elevation.models.PointElevationResult;
import java.util.Collections;
import java.util.List;

public final class BoundingBoxResultImpl implements BoundingBoxResult {
    private BoundingBoxResultInner innerObject;

    private final com.azure.maps.elevation.ElevationManager serviceManager;

    BoundingBoxResultImpl(
        BoundingBoxResultInner innerObject, com.azure.maps.elevation.ElevationManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public List<PointElevationResult> data() {
        List<PointElevationResult> inner = this.innerModel().data();
        if (inner != null) {
            return Collections.unmodifiableList(inner);
        } else {
            return Collections.emptyList();
        }
    }

    public BoundingBoxResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.elevation.ElevationManager manager() {
        return this.serviceManager;
    }
}
