// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.elevation.implementation;

import com.azure.core.http.HttpPipeline;
import com.azure.core.http.HttpPipelineBuilder;
import com.azure.core.http.policy.CookiePolicy;
import com.azure.core.http.policy.RetryPolicy;
import com.azure.core.http.policy.UserAgentPolicy;
import com.azure.core.util.serializer.JacksonAdapter;
import com.azure.core.util.serializer.SerializerAdapter;
import com.azure.maps.elevation.models.Geography;

/** Initializes a new instance of the ElevationClient type. */
public final class ElevationClientImpl {
    /**
     * Specifies which account is intended for usage in conjunction with the Azure AD security model. It represents a
     * unique ID for the Azure Maps account and can be retrieved from the Azure Maps management plane Account API. To
     * use Azure AD security in Azure Maps see the following [articles](https://aka.ms/amauthdetails) for guidance.
     */
    private final String xMsClientId;

    /**
     * Gets Specifies which account is intended for usage in conjunction with the Azure AD security model. It represents
     * a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management plane Account API. To
     * use Azure AD security in Azure Maps see the following [articles](https://aka.ms/amauthdetails) for guidance.
     *
     * @return the xMsClientId value.
     */
    public String getXMsClientId() {
        return this.xMsClientId;
    }

    /** This parameter specifies where the Azure Maps Creator resource is located. Valid values are us and eu. */
    private final Geography geography;

    /**
     * Gets This parameter specifies where the Azure Maps Creator resource is located. Valid values are us and eu.
     *
     * @return the geography value.
     */
    public Geography getGeography() {
        return this.geography;
    }

    /** Api Version. */
    private final String apiVersion;

    /**
     * Gets Api Version.
     *
     * @return the apiVersion value.
     */
    public String getApiVersion() {
        return this.apiVersion;
    }

    /** The HTTP pipeline to send requests through. */
    private final HttpPipeline httpPipeline;

    /**
     * Gets The HTTP pipeline to send requests through.
     *
     * @return the httpPipeline value.
     */
    public HttpPipeline getHttpPipeline() {
        return this.httpPipeline;
    }

    /** The serializer to serialize an object into a string. */
    private final SerializerAdapter serializerAdapter;

    /**
     * Gets The serializer to serialize an object into a string.
     *
     * @return the serializerAdapter value.
     */
    public SerializerAdapter getSerializerAdapter() {
        return this.serializerAdapter;
    }

    /** The ElevationsImpl object to access its operations. */
    private final ElevationsImpl elevations;

    /**
     * Gets the ElevationsImpl object to access its operations.
     *
     * @return the ElevationsImpl object.
     */
    public ElevationsImpl getElevations() {
        return this.elevations;
    }

    /**
     * Initializes an instance of ElevationClient client.
     *
     * @param xMsClientId Specifies which account is intended for usage in conjunction with the Azure AD security model.
     *     It represents a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management
     *     plane Account API. To use Azure AD security in Azure Maps see the following
     *     [articles](https://aka.ms/amauthdetails) for guidance.
     * @param geography This parameter specifies where the Azure Maps Creator resource is located. Valid values are us
     *     and eu.
     * @param apiVersion Api Version.
     */
    public ElevationClientImpl(String xMsClientId, Geography geography, String apiVersion) {
        this(
                new HttpPipelineBuilder()
                        .policies(new UserAgentPolicy(), new RetryPolicy(), new CookiePolicy())
                        .build(),
                JacksonAdapter.createDefaultSerializerAdapter(),
                xMsClientId,
                geography,
                apiVersion);
    }

    /**
     * Initializes an instance of ElevationClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param xMsClientId Specifies which account is intended for usage in conjunction with the Azure AD security model.
     *     It represents a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management
     *     plane Account API. To use Azure AD security in Azure Maps see the following
     *     [articles](https://aka.ms/amauthdetails) for guidance.
     * @param geography This parameter specifies where the Azure Maps Creator resource is located. Valid values are us
     *     and eu.
     * @param apiVersion Api Version.
     */
    public ElevationClientImpl(HttpPipeline httpPipeline, String xMsClientId, Geography geography, String apiVersion) {
        this(httpPipeline, JacksonAdapter.createDefaultSerializerAdapter(), xMsClientId, geography, apiVersion);
    }

    /**
     * Initializes an instance of ElevationClient client.
     *
     * @param httpPipeline The HTTP pipeline to send requests through.
     * @param serializerAdapter The serializer to serialize an object into a string.
     * @param xMsClientId Specifies which account is intended for usage in conjunction with the Azure AD security model.
     *     It represents a unique ID for the Azure Maps account and can be retrieved from the Azure Maps management
     *     plane Account API. To use Azure AD security in Azure Maps see the following
     *     [articles](https://aka.ms/amauthdetails) for guidance.
     * @param geography This parameter specifies where the Azure Maps Creator resource is located. Valid values are us
     *     and eu.
     * @param apiVersion Api Version.
     */
    public ElevationClientImpl(
            HttpPipeline httpPipeline,
            SerializerAdapter serializerAdapter,
            String xMsClientId,
            Geography geography,
            String apiVersion) {
        this.httpPipeline = httpPipeline;
        this.serializerAdapter = serializerAdapter;
        this.xMsClientId = xMsClientId;
        this.geography = geography;
        this.apiVersion = apiVersion;
        this.elevations = new ElevationsImpl(this);
    }
}
