// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.search.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.search.models.SearchPolygonResult;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** This object is returned from a successful Search Polygon call. */
@Immutable
public final class SearchPolygonResponseInner {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(SearchPolygonResponseInner.class);

    /*
     * Results array
     */
    @JsonProperty(value = "additionalData", access = JsonProperty.Access.WRITE_ONLY)
    private List<SearchPolygonResult> additionalData;

    /**
     * Get the additionalData property: Results array.
     *
     * @return the additionalData value.
     */
    public List<SearchPolygonResult> additionalData() {
        return this.additionalData;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (additionalData() != null) {
            additionalData().forEach(e -> e.validate());
        }
    }
}
