// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.traffic.implementation;

import com.azure.maps.traffic.fluent.models.TrafficIncidentViewportResultInner;
import com.azure.maps.traffic.models.TrafficIncidentViewportResult;
import com.azure.maps.traffic.models.TrafficIncidentViewportResultViewpResp;

public final class TrafficIncidentViewportResultImpl implements TrafficIncidentViewportResult {
    private TrafficIncidentViewportResultInner innerObject;

    private final com.azure.maps.traffic.TrafficManager serviceManager;

    TrafficIncidentViewportResultImpl(
        TrafficIncidentViewportResultInner innerObject, com.azure.maps.traffic.TrafficManager serviceManager) {
        this.innerObject = innerObject;
        this.serviceManager = serviceManager;
    }

    public TrafficIncidentViewportResultViewpResp viewpResp() {
        return this.innerModel().viewpResp();
    }

    public TrafficIncidentViewportResultInner innerModel() {
        return this.innerObject;
    }

    private com.azure.maps.traffic.TrafficManager manager() {
        return this.serviceManager;
    }
}
