// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;

/** The boolean type style rule object. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonTypeName("boolean")
@Fluent
public final class BooleanTypeStyleRule extends StyleObject {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(BooleanTypeStyleRule.class);

    /*
     * Boolean style rules.
     */
    @JsonProperty(value = "rules", required = true)
    private List<BooleanRuleObject> rules;

    /**
     * Get the rules property: Boolean style rules.
     *
     * @return the rules value.
     */
    public List<BooleanRuleObject> rules() {
        return this.rules;
    }

    /**
     * Set the rules property: Boolean style rules.
     *
     * @param rules the rules value to set.
     * @return the BooleanTypeStyleRule object itself.
     */
    public BooleanTypeStyleRule withRules(List<BooleanRuleObject> rules) {
        this.rules = rules;
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public BooleanTypeStyleRule withKeyName(String keyName) {
        super.withKeyName(keyName);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (rules() == null) {
            throw logger
                .logExceptionAsError(
                    new IllegalArgumentException("Missing required property rules in model BooleanTypeStyleRule"));
        } else {
            rules().forEach(e -> e.validate());
        }
    }
}
