// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** This object is returned from a successful Spatial Buffer call. */
@Fluent
public final class BufferResult {
    /*
     * The summary property.
     */
    @JsonProperty(value = "summary", access = JsonProperty.Access.WRITE_ONLY)
    private BufferSummary summary;

    /*
     * The FeatureCollection of buffers for the input.
     */
    @JsonProperty(value = "result")
    private GeoJsonFeatureCollection features;

    /**
     * Get the summary property: The summary property.
     *
     * @return the summary value.
     */
    public BufferSummary getSummary() {
        return this.summary;
    }

    /**
     * Get the features property: The FeatureCollection of buffers for the input.
     *
     * @return the features value.
     */
    public GeoJsonFeatureCollection getFeatures() {
        return this.features;
    }

    /**
     * Set the features property: The FeatureCollection of buffers for the input.
     *
     * @param features the features value to set.
     * @return the BufferResult object itself.
     */
    public BufferResult setFeatures(GeoJsonFeatureCollection features) {
        this.features = features;
        return this;
    }
}
