// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.maps.creator.fluent.models.CollectionInfoInner;
import java.util.List;

/** An immutable client-side representation of CollectionInfo. */
public interface CollectionInfo {
    /**
     * Gets the name property: identifier of the collection used, for example, in URIs.
     *
     * @return the name value.
     */
    String name();

    /**
     * Gets the title property: human readable title of the collection.
     *
     * @return the title value.
     */
    String title();

    /**
     * Gets the ontology property: The ontology version of this dataset.
     *
     * @return the ontology value.
     */
    String ontology();

    /**
     * Gets the description property: a description of the features in the collection.
     *
     * @return the description value.
     */
    String description();

    /**
     * Gets the links property: Links to other WFS endpoints.
     *
     * @return the links value.
     */
    List<WfsEndpointLink> links();

    /**
     * Gets the inner com.azure.maps.creator.fluent.models.CollectionInfoInner object.
     *
     * @return the inner object.
     */
    CollectionInfoInner innerModel();
}
