// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.azure.maps.creator.fluent.models.DatasetDetailInfoInner;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The response model for the Dataset List API. The response body will contain a list of all the previously created
 * datasets.
 */
@Immutable
public final class DatasetListResponse {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(DatasetListResponse.class);

    /*
     * A list of all the previously created datasets.
     */
    @JsonProperty(value = "datasets", access = JsonProperty.Access.WRITE_ONLY)
    private List<DatasetDetailInfoInner> datasets;

    /*
     * If present, the location of the next page of data.
     */
    @JsonProperty(value = "nextLink", access = JsonProperty.Access.WRITE_ONLY)
    private String nextLink;

    /**
     * Get the datasets property: A list of all the previously created datasets.
     *
     * @return the datasets value.
     */
    public List<DatasetDetailInfoInner> datasets() {
        return this.datasets;
    }

    /**
     * Get the nextLink property: If present, the location of the next page of data.
     *
     * @return the nextLink value.
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (datasets() != null) {
            datasets().forEach(e -> e.validate());
        }
    }
}
