// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.maps.creator.fluent.models.ExtendedGeoJsonFeatureCollectionInner;
import java.util.List;

/** An immutable client-side representation of ExtendedGeoJsonFeatureCollection. */
public interface ExtendedGeoJsonFeatureCollection {
    /**
     * Gets the features property: Contains a list of valid `GeoJSON Feature` objects.
     *
     * @return the features value.
     */
    List<GeoJsonFeature> features();

    /**
     * Gets the ontology property: The ontology version of this dataset.
     *
     * @return the ontology value.
     */
    String ontology();

    /**
     * Gets the numberReturned property: Number of returned features.
     *
     * @return the numberReturned value.
     */
    Integer numberReturned();

    /**
     * Gets the links property: Links to other WFS endpoints.
     *
     * @return the links value.
     */
    List<WfsEndpointLink> links();

    /**
     * Gets the inner com.azure.maps.creator.fluent.models.ExtendedGeoJsonFeatureCollectionInner object.
     *
     * @return the inner object.
     */
    ExtendedGeoJsonFeatureCollectionInner innerModel();
}
