// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.maps.creator.fluent.models.FeatureResponseInner;
import java.util.List;

/** An immutable client-side representation of FeatureResponse. */
public interface FeatureResponse {
    /**
     * Gets the ontology property: The ontology version of this dataset.
     *
     * @return the ontology value.
     */
    String ontology();

    /**
     * Gets the feature property: A valid `GeoJSON Feature` object type. Please refer to [RFC
     * 7946](https://tools.ietf.org/html/rfc7946#section-3.2) for details.
     *
     * @return the feature value.
     */
    GeoJsonFeature feature();

    /**
     * Gets the links property: Links to other WFS endpoints.
     *
     * @return the links value.
     */
    List<WfsEndpointLink> links();

    /**
     * Gets the inner com.azure.maps.creator.fluent.models.FeatureResponseInner object.
     *
     * @return the inner object.
     */
    FeatureResponseInner innerModel();
}
