// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.maps.creator.fluent.models.GreatCircleDistanceResponseInner;

/** An immutable client-side representation of GreatCircleDistanceResponse. */
public interface GreatCircleDistanceResponse {
    /**
     * Gets the summary property: Summary object.
     *
     * @return the summary value.
     */
    GreatCircleDistanceResponseSummary summary();

    /**
     * Gets the result property: Result Object.
     *
     * @return the result value.
     */
    GreatCircleDistanceResponseResult result();

    /**
     * Gets the inner com.azure.maps.creator.fluent.models.GreatCircleDistanceResponseInner object.
     *
     * @return the inner object.
     */
    GreatCircleDistanceResponseInner innerModel();
}
