// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/** This object is returned from a successful Great Circle Distance call. */
@Immutable
public final class GreatCircleDistanceResult {
    /*
     * Summary object
     */
    @JsonProperty(value = "summary", access = JsonProperty.Access.WRITE_ONLY)
    private GreatCircleDistanceSummary summary;

    /*
     * Result Object
     */
    @JsonProperty(value = "result", access = JsonProperty.Access.WRITE_ONLY)
    private GreatCircleDistanceResultAutoGenerated result;

    /**
     * Get the summary property: Summary object.
     *
     * @return the summary value.
     */
    public GreatCircleDistanceSummary getSummary() {
        return this.summary;
    }

    /**
     * Get the result property: Result Object.
     *
     * @return the result value.
     */
    public GreatCircleDistanceResultAutoGenerated getResult() {
        return this.result;
    }
}
