// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Detail information for the data. */
@Fluent
public final class MapData {
    /*
     * The unique data id for the data.
     */
    @JsonProperty(value = "udid", access = JsonProperty.Access.WRITE_ONLY)
    private String udid;

    /*
     * The location of the data. Execute a HTTP `GET` on this location to
     * download the data.
     */
    @JsonProperty(value = "location", access = JsonProperty.Access.WRITE_ONLY)
    private String locationURL;

    /*
     * The size of the content in bytes.
     */
    @JsonProperty(value = "sizeInBytes", access = JsonProperty.Access.WRITE_ONLY)
    private Long sizeInBytes;

    /*
     * The current upload status of the content.
     */
    @JsonProperty(value = "uploadStatus", access = JsonProperty.Access.WRITE_ONLY)
    private UploadStatus uploadStatus;

    /*
     * The dataFormat property.
     */
    @JsonProperty(value = "dataFormat")
    private DataFormat dataFormat;

    /*
     * The current description.
     */
    @JsonProperty(value = "description", access = JsonProperty.Access.WRITE_ONLY)
    private String description;

    /**
     * Get the udid property: The unique data id for the data.
     *
     * @return the udid value.
     */
    public String getUdid() {
        return this.udid;
    }

    /**
     * Get the locationURL property: The location of the data. Execute a HTTP `GET` on this location to download the
     * data.
     *
     * @return the locationURL value.
     */
    public String getLocationURL() {
        return this.locationURL;
    }

    /**
     * Get the sizeInBytes property: The size of the content in bytes.
     *
     * @return the sizeInBytes value.
     */
    public Long getSizeInBytes() {
        return this.sizeInBytes;
    }

    /**
     * Get the uploadStatus property: The current upload status of the content.
     *
     * @return the uploadStatus value.
     */
    public UploadStatus getUploadStatus() {
        return this.uploadStatus;
    }

    /**
     * Get the dataFormat property: The dataFormat property.
     *
     * @return the dataFormat value.
     */
    public DataFormat getDataFormat() {
        return this.dataFormat;
    }

    /**
     * Set the dataFormat property: The dataFormat property.
     *
     * @param dataFormat the dataFormat value to set.
     * @return the MapData object itself.
     */
    public MapData setDataFormat(DataFormat dataFormat) {
        this.dataFormat = dataFormat;
        return this;
    }

    /**
     * Get the description property: The current description.
     *
     * @return the description value.
     */
    public String getDescription() {
        return this.description;
    }
}
