// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/** Defines values for OutputOntology. */
public final class OutputOntology extends ExpandableStringEnum<OutputOntology> {
    /** Static value facility-2.0 for OutputOntology. */
    public static final OutputOntology FACILITY20 = fromString("facility-2.0");

    /**
     * Creates or finds a OutputOntology from its string representation.
     *
     * @param name a name to look for.
     * @return the corresponding OutputOntology.
     */
    @JsonCreator
    public static OutputOntology fromString(String name) {
        return fromString(name, OutputOntology.class);
    }

    /** @return known OutputOntology values. */
    public static Collection<OutputOntology> values() {
        return values(OutputOntology.class);
    }
}
