// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Parameter group. */
@Fluent
public final class Position {
    /*
     * The latitude of the location being passed.  Example: 48.36.
     */
    @JsonProperty(value = "Latitude", required = true)
    private float latitude;

    /*
     * The longitude of the location being passed.  Example: -124.63.
     */
    @JsonProperty(value = "Longitude", required = true)
    private float longitude;

    /**
     * Get the latitude property: The latitude of the location being passed. Example: 48.36.
     *
     * @return the latitude value.
     */
    public float getLatitude() {
        return this.latitude;
    }

    /**
     * Set the latitude property: The latitude of the location being passed. Example: 48.36.
     *
     * @param latitude the latitude value to set.
     * @return the Position object itself.
     */
    public Position setLatitude(float latitude) {
        this.latitude = latitude;
        return this;
    }

    /**
     * Get the longitude property: The longitude of the location being passed. Example: -124.63.
     *
     * @return the longitude value.
     */
    public float getLongitude() {
        return this.longitude;
    }

    /**
     * Set the longitude property: The longitude of the location being passed. Example: -124.63.
     *
     * @param longitude the longitude value to set.
     * @return the Position object itself.
     */
    public Position setLongitude(float longitude) {
        this.longitude = longitude;
        return this;
    }
}
