// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpRequest;
import com.azure.core.http.rest.ResponseBase;
import com.azure.maps.creator.fluent.models.GeofenceResponseInner;

/** Contains all response data for the postGeofence operation. */
public final class SpatialsPostGeofenceResponse
    extends ResponseBase<SpatialsPostGeofenceHeaders, GeofenceResponseInner> {
    /**
     * Creates an instance of SpatialsPostGeofenceResponse.
     *
     * @param request the request which resulted in this SpatialsPostGeofenceResponse.
     * @param statusCode the status code of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param value the deserialized value of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     */
    public SpatialsPostGeofenceResponse(
        HttpRequest request,
        int statusCode,
        HttpHeaders rawHeaders,
        GeofenceResponseInner value,
        SpatialsPostGeofenceHeaders headers) {
        super(request, statusCode, rawHeaders, value, headers);
    }

    /** @return the deserialized response body. */
    @Override
    public GeofenceResponseInner getValue() {
        return super.getValue();
    }
}
