// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.creator.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;

/** The string type style rule object. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonTypeName("string")
@Fluent
public final class StringTypeStyleRule extends StyleObject {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(StringTypeStyleRule.class);

    /*
     * String style rules.
     */
    @JsonProperty(value = "rules", required = true)
    private List<Map<String, String>> rules;

    /**
     * Get the rules property: String style rules.
     *
     * @return the rules value.
     */
    public List<Map<String, String>> rules() {
        return this.rules;
    }

    /**
     * Set the rules property: String style rules.
     *
     * @param rules the rules value to set.
     * @return the StringTypeStyleRule object itself.
     */
    public StringTypeStyleRule withRules(List<Map<String, String>> rules) {
        this.rules = rules;
        return this;
    }

    /** {@inheritDoc} */
    @Override
    public StringTypeStyleRule withKeyName(String keyName) {
        super.withKeyName(keyName);
        return this;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    @Override
    public void validate() {
        super.validate();
        if (rules() == null) {
            throw logger
                .logExceptionAsError(
                    new IllegalArgumentException("Missing required property rules in model StringTypeStyleRule"));
        }
    }
}
