// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.route.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Effective parameter or data used when calling this Route API. */
@Immutable
public final class RouteResponseReportEffectiveSetting {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(RouteResponseReportEffectiveSetting.class);

    /*
     * Name of the parameter used.
     */
    @JsonProperty(value = "key", access = JsonProperty.Access.WRITE_ONLY)
    private String key;

    /*
     * Value of the parameter used.
     */
    @JsonProperty(value = "value", access = JsonProperty.Access.WRITE_ONLY)
    private String value;

    /**
     * Get the key property: Name of the parameter used.
     *
     * @return the key value.
     */
    public String key() {
        return this.key;
    }

    /**
     * Get the value property: Value of the parameter used.
     *
     * @return the value value.
     */
    public String value() {
        return this.value;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
