// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.route.models;

import com.azure.core.annotation.Immutable;
import com.azure.core.util.logging.ClientLogger;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** The RouteDirectionsResult model. */
@Immutable
public final class RouteDirectionsResult {
    @JsonIgnore private final ClientLogger logger = new ClientLogger(RouteDirectionsResult.class);

    /*
     * Summary object
     */
    @JsonProperty(value = "summary", access = JsonProperty.Access.WRITE_ONLY)
    private RouteDirectionsSummary summary;

    /*
     * Legs array
     */
    @JsonProperty(value = "legs", access = JsonProperty.Access.WRITE_ONLY)
    private List<RouteResultLeg> legs;

    /*
     * Sections array
     */
    @JsonProperty(value = "sections", access = JsonProperty.Access.WRITE_ONLY)
    private List<RouteResultSection> sections;

    /*
     * Contains guidance related elements. This field is present only when
     * guidance was requested and is available.
     */
    @JsonProperty(value = "guidance", access = JsonProperty.Access.WRITE_ONLY)
    private RouteResultGuidance guidance;

    /**
     * Get the summary property: Summary object.
     *
     * @return the summary value.
     */
    public RouteDirectionsSummary summary() {
        return this.summary;
    }

    /**
     * Get the legs property: Legs array.
     *
     * @return the legs value.
     */
    public List<RouteResultLeg> legs() {
        return this.legs;
    }

    /**
     * Get the sections property: Sections array.
     *
     * @return the sections value.
     */
    public List<RouteResultSection> sections() {
        return this.sections;
    }

    /**
     * Get the guidance property: Contains guidance related elements. This field is present only when guidance was
     * requested and is available.
     *
     * @return the guidance value.
     */
    public RouteResultGuidance guidance() {
        return this.guidance;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
        if (summary() != null) {
            summary().validate();
        }
        if (legs() != null) {
            legs().forEach(e -> e.validate());
        }
        if (sections() != null) {
            sections().forEach(e -> e.validate());
        }
        if (guidance() != null) {
            guidance().validate();
        }
    }
}
