/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.batch.protocol.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The status of the Job Preparation and Job Release Tasks on a Compute Node.
 */
public class JobPreparationAndReleaseTaskExecutionInformation {
    /**
     * The ID of the Pool containing the Compute Node to which this entry
     * refers.
     */
    @JsonProperty(value = "poolId")
    private String poolId;

    /**
     * The ID of the Compute Node to which this entry refers.
     */
    @JsonProperty(value = "nodeId")
    private String nodeId;

    /**
     * The URL of the Compute Node to which this entry refers.
     */
    @JsonProperty(value = "nodeUrl")
    private String nodeUrl;

    /**
     * Information about the execution status of the Job Preparation Task on
     * this Compute Node.
     */
    @JsonProperty(value = "jobPreparationTaskExecutionInfo")
    private JobPreparationTaskExecutionInformation jobPreparationTaskExecutionInfo;

    /**
     * Information about the execution status of the Job Release Task on this
     * Compute Node. This property is set only if the Job Release Task has run
     * on the Compute Node.
     */
    @JsonProperty(value = "jobReleaseTaskExecutionInfo")
    private JobReleaseTaskExecutionInformation jobReleaseTaskExecutionInfo;

    /**
     * Get the ID of the Pool containing the Compute Node to which this entry refers.
     *
     * @return the poolId value
     */
    public String poolId() {
        return this.poolId;
    }

    /**
     * Set the ID of the Pool containing the Compute Node to which this entry refers.
     *
     * @param poolId the poolId value to set
     * @return the JobPreparationAndReleaseTaskExecutionInformation object itself.
     */
    public JobPreparationAndReleaseTaskExecutionInformation withPoolId(String poolId) {
        this.poolId = poolId;
        return this;
    }

    /**
     * Get the ID of the Compute Node to which this entry refers.
     *
     * @return the nodeId value
     */
    public String nodeId() {
        return this.nodeId;
    }

    /**
     * Set the ID of the Compute Node to which this entry refers.
     *
     * @param nodeId the nodeId value to set
     * @return the JobPreparationAndReleaseTaskExecutionInformation object itself.
     */
    public JobPreparationAndReleaseTaskExecutionInformation withNodeId(String nodeId) {
        this.nodeId = nodeId;
        return this;
    }

    /**
     * Get the URL of the Compute Node to which this entry refers.
     *
     * @return the nodeUrl value
     */
    public String nodeUrl() {
        return this.nodeUrl;
    }

    /**
     * Set the URL of the Compute Node to which this entry refers.
     *
     * @param nodeUrl the nodeUrl value to set
     * @return the JobPreparationAndReleaseTaskExecutionInformation object itself.
     */
    public JobPreparationAndReleaseTaskExecutionInformation withNodeUrl(String nodeUrl) {
        this.nodeUrl = nodeUrl;
        return this;
    }

    /**
     * Get information about the execution status of the Job Preparation Task on this Compute Node.
     *
     * @return the jobPreparationTaskExecutionInfo value
     */
    public JobPreparationTaskExecutionInformation jobPreparationTaskExecutionInfo() {
        return this.jobPreparationTaskExecutionInfo;
    }

    /**
     * Set information about the execution status of the Job Preparation Task on this Compute Node.
     *
     * @param jobPreparationTaskExecutionInfo the jobPreparationTaskExecutionInfo value to set
     * @return the JobPreparationAndReleaseTaskExecutionInformation object itself.
     */
    public JobPreparationAndReleaseTaskExecutionInformation withJobPreparationTaskExecutionInfo(JobPreparationTaskExecutionInformation jobPreparationTaskExecutionInfo) {
        this.jobPreparationTaskExecutionInfo = jobPreparationTaskExecutionInfo;
        return this;
    }

    /**
     * Get information about the execution status of the Job Release Task on this Compute Node. This property is set only if the Job Release Task has run on the Compute Node.
     *
     * @return the jobReleaseTaskExecutionInfo value
     */
    public JobReleaseTaskExecutionInformation jobReleaseTaskExecutionInfo() {
        return this.jobReleaseTaskExecutionInfo;
    }

    /**
     * Set information about the execution status of the Job Release Task on this Compute Node. This property is set only if the Job Release Task has run on the Compute Node.
     *
     * @param jobReleaseTaskExecutionInfo the jobReleaseTaskExecutionInfo value to set
     * @return the JobPreparationAndReleaseTaskExecutionInformation object itself.
     */
    public JobPreparationAndReleaseTaskExecutionInformation withJobReleaseTaskExecutionInfo(JobReleaseTaskExecutionInformation jobReleaseTaskExecutionInfo) {
        this.jobReleaseTaskExecutionInfo = jobReleaseTaskExecutionInfo;
        return this;
    }

}
