/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.batch.protocol.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The configuration for virtual machine extension instance view.
 */
public class NodeVMExtension {
    /**
     * The provisioning state of the virtual machine extension.
     */
    @JsonProperty(value = "provisioningState")
    private String provisioningState;

    /**
     * The virtual machine extension.
     */
    @JsonProperty(value = "vmExtension")
    private VMExtension vmExtension;

    /**
     * The vm extension instance view.
     */
    @JsonProperty(value = "instanceView")
    private VMExtensionInstanceView instanceView;

    /**
     * Get the provisioning state of the virtual machine extension.
     *
     * @return the provisioningState value
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Set the provisioning state of the virtual machine extension.
     *
     * @param provisioningState the provisioningState value to set
     * @return the NodeVMExtension object itself.
     */
    public NodeVMExtension withProvisioningState(String provisioningState) {
        this.provisioningState = provisioningState;
        return this;
    }

    /**
     * Get the virtual machine extension.
     *
     * @return the vmExtension value
     */
    public VMExtension vmExtension() {
        return this.vmExtension;
    }

    /**
     * Set the virtual machine extension.
     *
     * @param vmExtension the vmExtension value to set
     * @return the NodeVMExtension object itself.
     */
    public NodeVMExtension withVmExtension(VMExtension vmExtension) {
        this.vmExtension = vmExtension;
        return this;
    }

    /**
     * Get the vm extension instance view.
     *
     * @return the instanceView value
     */
    public VMExtensionInstanceView instanceView() {
        return this.instanceView;
    }

    /**
     * Set the vm extension instance view.
     *
     * @param instanceView the instanceView value to set
     * @return the NodeVMExtension object itself.
     */
    public NodeVMExtension withInstanceView(VMExtensionInstanceView instanceView) {
        this.instanceView = instanceView;
        return this;
    }

}
