/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.batch.protocol.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Information about a file or directory on a Compute Node.
 */
public class NodeFile {
    /**
     * The file path.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The URL of the file.
     */
    @JsonProperty(value = "url")
    private String url;

    /**
     * Whether the object represents a directory.
     */
    @JsonProperty(value = "isDirectory")
    private Boolean isDirectory;

    /**
     * The file properties.
     */
    @JsonProperty(value = "properties")
    private FileProperties properties;

    /**
     * Get the file path.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the file path.
     *
     * @param name the name value to set
     * @return the NodeFile object itself.
     */
    public NodeFile withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the URL of the file.
     *
     * @return the url value
     */
    public String url() {
        return this.url;
    }

    /**
     * Set the URL of the file.
     *
     * @param url the url value to set
     * @return the NodeFile object itself.
     */
    public NodeFile withUrl(String url) {
        this.url = url;
        return this;
    }

    /**
     * Get whether the object represents a directory.
     *
     * @return the isDirectory value
     */
    public Boolean isDirectory() {
        return this.isDirectory;
    }

    /**
     * Set whether the object represents a directory.
     *
     * @param isDirectory the isDirectory value to set
     * @return the NodeFile object itself.
     */
    public NodeFile withIsDirectory(Boolean isDirectory) {
        this.isDirectory = isDirectory;
        return this;
    }

    /**
     * Get the file properties.
     *
     * @return the properties value
     */
    public FileProperties properties() {
        return this.properties;
    }

    /**
     * Set the file properties.
     *
     * @param properties the properties value to set
     * @return the NodeFile object itself.
     */
    public NodeFile withProperties(FileProperties properties) {
        this.properties = properties;
        return this;
    }

}
