// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.maps.elevation.models;

import com.azure.maps.elevation.fluent.models.BoundingBoxResultInner;
import java.util.List;

/** An immutable client-side representation of BoundingBoxResult. */
public interface BoundingBoxResult {
    /**
     * Gets the data property: The response from the Get Data for Bounding Box API. The results are ordered starting
     * with the southwest corner, and then proceed west to east and south to north.
     *
     * @return the data value.
     */
    List<PointElevationResult> data();

    /**
     * Gets the inner com.azure.maps.elevation.fluent.models.BoundingBoxResultInner object.
     *
     * @return the inner object.
     */
    BoundingBoxResultInner innerModel();
}
